print ('Welcome to Rock, Paper, Scissors, Lizard, Spock!')
print ('')
print ('Please choose two players: ')
print ('1 : Human')
print ('2 : StupidBot')
print ('3 : RandomBot')
print ('4 : IterativeBot')
print ('5 : LastPlayBot')
print ('6 : MyBot')