# Generated by Django 2.2.5 on 2019-11-21 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCatalogue',
            fields=[
                ('card_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=30, unique=True)),
                ('top_value', models.IntegerField()),
                ('left_value', models.IntegerField()),
                ('right_value', models.IntegerField()),
                ('bottom_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('p_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card1create', to='myapp.CardCatalogue')),
                ('card2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card2create', to='myapp.CardCatalogue')),
                ('card3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card3create', to='myapp.CardCatalogue')),
                ('card4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card4create', to='myapp.CardCatalogue')),
                ('card5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card5create', to='myapp.CardCatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=240)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Input')),
            ],
        ),
    ]
