# Generated by Django 2.2.5 on 2019-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='input2',
            field=models.CharField(default='old_input', max_length=300),
            preserve_default=False,
        ),
    ]
