# Generated by Django 2.2.5 on 2019-09-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_input_input2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='input2',
        ),
    ]
