# Generated by Django 2.2.5 on 2019-11-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20191121_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deck_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Deck')),
            ],
        ),
    ]
