# Generated by Django 2.2.5 on 2019-11-30 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_from', to=settings.AUTH_USER_MODEL)),
                ('user_from_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_from_deck', to='myapp.Deck')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_to', to=settings.AUTH_USER_MODEL)),
                ('user_to_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_to_deck', to='myapp.Deck')),
            ],
        ),
    ]
