# Generated by Django 2.2.5 on 2019-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cardcatalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcatalogue',
            name='times_card_played',
            field=models.IntegerField(default=0),
        ),
    ]
