# Generated by Django 2.2.5 on 2019-12-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_versus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
