# Generated by Django 2.2.5 on 2019-11-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191111_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='cardcatalogue',
            name='bottom_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardcatalogue',
            name='left_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardcatalogue',
            name='right_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardcatalogue',
            name='top_value',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('p_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Players')),
                ('matches_total', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('deck_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=10)),
                ('times_deck_played', models.IntegerField(default=0)),
                ('cardCatalogue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.CardCatalogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Players')),
            ],
        ),
        migrations.CreateModel(
            name='Deck_Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_card_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_id2', to='myapp.CardCatalogue')),
                ('de_desk_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desk_id2', to='myapp.Decks')),
            ],
        ),
    ]
